### ISSUE TITLE
Disappeared scrollTop logo while refreshing the site

### ISSUE THREAD

**Issue by MastooraTurkmen** [MastooraTurkmen/Paper-Airplanes-Project#7]
After reloading and saving multiple times, the scrollTop disappeared and came after a few seconds.
Do you have any idea about that?

**Comment by MastooraTurkmen** [comment]
I reloaded the site and the logo just disappeared: 

![image](https://github.com/user-attachments/assets/4c924222-db90-4cdf-bdef-c7345ff53a43)

**Comment by alisajad001** [comment]
I think it's the z-index problem.

**Comment by alisajad001** [comment]
It is fixed now.

**Comment by MastooraTurkmen** [comment]
Thank you
